name: Deploy to Cloud Storage and Invalidate CDN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: t-science-434802-f8
          export_default_credentials: true

      - name: Deploy to Cloud Storage
        run: |
          gsutil -m rsync -r ./ gs://www.theadarsha.net
